# Pipeline RAG completo — Regulamento Geral da Graduação da UFRPE

Este é o notebook principal. O corpus é o **Regulamento Geral da Graduação (PREG/UFRPE, 2024)**, dividido em 30 documentos temáticos por `split_regulamento.py` (um ou mais Títulos/Capítulos por documento, por exemplo matrícula, suspensão de programa, monitoria e glossário). O notebook lê os PDFs de `documents/`, cria chunks de tamanho fixo com overlap, persiste embeddings no ChromaDB e compara os dois métodos de retrieval:

- **esparso:** TF-IDF com similaridade cosseno;
- **denso:** embeddings Gemini com similaridade cosseno no ChromaDB.

Ao final, três perguntas são respondidas sem retrieval e com os dois retrievers. Uma pergunta demonstrativa adicional completa as 10 respostas da avaliação manual.

Para regenerar o corpus: `python split_regulamento.py "Regulamento geral PREG 2024.pdf" documents`.

## 1. Modelos, caminhos e banco

In [ ]:
import os
from pathlib import Path
from pprint import pprint

import chromadb
from dotenv import load_dotenv
from google import genai

import rag_utils

PROJECT_ROOT = Path.cwd()
DATA_DIR = PROJECT_ROOT / "documents"
CHROMA_DIR = PROJECT_ROOT / "db" / "chroma"
COLLECTION_NAME = "regulamento_ufrpe_v1"
EMBED_MODEL = "gemini-embedding-001"
GEN_MODEL = "gemini-3.1-flash-lite"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 150
TOP_K = 5

load_dotenv(PROJECT_ROOT / ".env")
API_KEY = os.environ.get("GEMINI_API_KEY")
assert API_KEY, "Defina GEMINI_API_KEY no arquivo .env da raiz do projeto."

client = genai.Client(api_key=API_KEY)
embedder = rag_utils.GeminiEmbedder(client, model=EMBED_MODEL)
chroma_client = chromadb.PersistentClient(path=str(CHROMA_DIR))
collection = chroma_client.get_or_create_collection(
    name=COLLECTION_NAME, metadata={"hnsw:space": "cosine"}
)
print(f"Documentos: {DATA_DIR}")
print(f"Banco: {CHROMA_DIR}")

Documentos: C:\Users\User\Desktop\Mineração\rag-practice\documents
Banco: C:\Users\User\Desktop\Mineração\rag-practice\db\chroma

## 2. Ingestão e indexação

A indexação é retomável: chunks já presentes no banco não são enviados novamente à API de embeddings.

In [ ]:
pdf_paths = rag_utils.iter_pdfs(DATA_DIR)
records = rag_utils.load_corpus(DATA_DIR, CHUNK_SIZE, CHUNK_OVERLAP)
assert records, f"Nenhum conteúdo PDF foi encontrado em {DATA_DIR}."

index_stats = rag_utils.index_dense_collection(collection, records, embedder)
print(f"PDFs: {len(pdf_paths)}")
print(f"Chunks: {len(records)}")
print(index_stats)

PDFs: 30
Chunks: 274
{'total': 274, 'already_indexed': 0, 'indexed_now': 274}

## 3. Os dois métodos de retrieval

Ambos usam exatamente os mesmos chunks. O método denso consulta os vetores persistidos no Chroma; o TF-IDF monta um índice esparso local a partir dos textos guardados no mesmo banco.

In [ ]:
indexed_records = rag_utils.records_from_collection(collection)
dense_retriever = rag_utils.DenseRetriever(collection, embedder)
tfidf_retriever = rag_utils.TfidfRetriever(indexed_records)

dense_rag = rag_utils.RAGAssistant(client, dense_retriever, GEN_MODEL)
tfidf_rag = rag_utils.RAGAssistant(client, tfidf_retriever, GEN_MODEL)

In [ ]:
sample_question = "Por quanto tempo um(a) discente pode manter a condição de aluno especial?"

print("Ranking denso:")
pprint(rag_utils.hits_as_rows(dense_retriever.retrieve(sample_question, TOP_K)), sort_dicts=False)
print("\nRanking TF-IDF:")
pprint(rag_utils.hits_as_rows(tfidf_retriever.retrieve(sample_question, TOP_K)), sort_dicts=False)

Ranking denso:

[{'rank': 1,
  'cosine_similarity': 0.7459,
  'paper': '10_aluno_especial_ordinario',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Alunos especiais de graduação e aluno especial ordinário\n'
             'TÍTULO IX\n'
             'DOS ALUNOS ESPECIAIS DE GRADUAÇÃO\n'
             'Art. 180. O(A) discente de graduação admitido(a) através de '
             'qualque…'},
 {'rank': 2,
  'cosine_similarity': 0.7409,
  'paper': '10_aluno_especial_ordinario',
  'page': 2,
  'chunk': 2,
  'snippet': 'is ordinários, além das restrições que se aplicam a todos(as) '
             'os(as)\n'
             'alunos(as) especiais, definidas no Art. 181, não podem: - '
             'solicitar e outros bens da UFRPE;\n'
             'I - realizar estágio;\n'
             'II - matricular-se em componentes cur…'},
 {'rank': 3,
  'cosine_similarity': 0.7323,
  'paper': '12_complementacao_movimentacao_temporaria',
  'page': 1,
  'chunk': 3,
  'snippet': 'dos podem se matricular em turma\n'
             'que venha a ser oferecida nos períodos letivos especiais de '
             'férias, desde que o componente curricular\n'
             'integre seu plano de estudos.\n'
             'Art. 208. Os(As) alunos(as) especiais em complementação…'},
 {'rank': 4,
  'cosine_similarity': 0.7308,
  'paper': '10_aluno_especial_ordinario',
  'page': 1,
  'chunk': 2,
  'snippet': 's\n'
             'curriculares que fazem parte do plano de estudos apresentado '
             'previamente pelo(a) discente e que\n'
             'tenham sido registrados no Sistema Integrado de Atividades '
             'Acadêmicas como deferidos.\n'
             '§ 3º O deferimento da solicitação de…'},
 {'rank': 5,
  'cosine_similarity': 0.7242,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 2,
  'chunk': 3,
  'snippet': 'e.\n'
             '§ 3º A solicitação de recurso para permanência no curso deve ser '
             'através de processo eletrônico com\n'
             'requerimento substanciado por justificativa.\n'
             '§ 4º O recurso deve ser avaliado pela COAA, com decisão do CCD '
             'do curso.…'}]

Ranking TF-IDF:
[{'rank': 1,
  'tfidf_cosine_similarity': 0.3792,
  'paper': '10_aluno_especial_ordinario',
  'page': 1,
  'chunk': 2,
  'snippet': 's\n'
             'curriculares que fazem parte do plano de estudos apresentado '
             'previamente pelo(a) discente e que\n'
             'tenham sido registrados no Sistema Integrado de Atividades '
             'Acadêmicas como deferidos.\n'
             '§ 3º O deferimento da solicitação de…'},
 {'rank': 2,
  'tfidf_cosine_similarity': 0.3724,
  'paper': '10_aluno_especial_ordinario',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Alunos especiais de graduação e aluno especial ordinário\n'
             'TÍTULO IX\n'
             'DOS ALUNOS ESPECIAIS DE GRADUAÇÃO\n'
             'Art. 180. O(A) discente de graduação admitido(a) através de '
             'qualque…'},
 {'rank': 3,
  'tfidf_cosine_similarity': 0.2538,
  'paper': '12_complementacao_movimentacao_temporaria',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Complementação de estudos e regime especial de movimentação\n'
             'temporária\n'
             'CAPÍTULO III\n'
             'DO ALUNO ESPECIAL EM COMPLEMENTAÇÃO DE ESTUDOS\n'
             'Art. 203. É permitido o ingresso na U…'},
 {'rank': 4,
  'tfidf_cosine_similarity': 0.2457,
  'paper': '10_aluno_especial_ordinario',
  'page': 1,
  'chunk': 3,
  'snippet': 'de estudos.\n'
             'CAPÍTULO I\n'
             'DO ALUNO ESPECIAL ORDINÁRIO\n'
             'Art. 186. O ingresso como aluno(a) especial ordinário deve ser '
             'solicitado ao DRCA, no prazo definido\n'
             'no Calendário Acadêmico e através de processo eletrônico, '
             'mediante a…'},
 {'rank': 5,
  'tfidf_cosine_similarity': 0.211,
  'paper': '11_mobilidade_academica',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Mobilidade acadêmica: aluno especial em mobilidade e permissão\n'
             'para cursar componentes em mobilidade\n'
             'CAPÍTULO II\n'
             'DO ALUNO ESPECIAL EM MOBILIDADE\n'
             'Art. 190. É permitido o…'}]

## 4. Geração fundamentada

O prompt contém os top-k chunks completos e exige citações no formato `[documento, p. N, trecho M]`.

In [ ]:
demo_result = dense_rag.ask(sample_question, k=TOP_K)
print(demo_result.answer)

A condição de aluno especial tem duração limitada a quatro períodos letivos consecutivos [10_aluno_especial_ordinario, p. 1, trecho 0].

## 5. Três perguntas: sem retrieval, RAG denso e RAG TF-IDF

Esta célula gera nove respostas comparáveis. Somadas à demonstração acima, são as 10 respostas usadas na avaliação manual.

In [ ]:
QUESTIONS = [
    "Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?",
    "Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?",
    "Como é calculada a nota final da seleção para monitoria?",
]

generated_answers = [
    {"question": sample_question, "method": "dense", "answer": demo_result.answer}
]

for question in QUESTIONS:
    baseline = rag_utils.answer_without_retrieval(client, question, GEN_MODEL)
    dense_result = dense_rag.ask(question, k=TOP_K)
    tfidf_result = tfidf_rag.ask(question, k=TOP_K)

    generated_answers.extend([
        {"question": question, "method": "no_retrieval", "answer": baseline},
        {"question": question, "method": "dense", "answer": dense_result.answer},
        {"question": question, "method": "tfidf", "answer": tfidf_result.answer},
    ])

    print(f"\n{'=' * 90}\nPERGUNTA: {question}")
    print(f"\nSEM RETRIEVAL\n{baseline}")
    print("\nCHUNKS — DENSO")
    pprint(rag_utils.hits_as_rows(dense_result.hits), sort_dicts=False)
    print(f"\nRAG DENSO\n{dense_result.answer}")
    print("\nCHUNKS — TF-IDF")
    pprint(rag_utils.hits_as_rows(tfidf_result.hits), sort_dicts=False)
    print(f"\nRAG TF-IDF\n{tfidf_result.answer}")

assert len(generated_answers) == 10

==========================================================================================
PERGUNTA: Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?

SEM RETRIEVAL
Para responder à sua pergunta com precisão, é necessário esclarecer que as regras sobre suspensão de programas (seja acadêmico, de benefícios governamentais ou de planos de saúde) **variam drasticamente dependendo do regulamento específico** de cada instituição ou contrato.

Como você não especificou a qual programa se refere, aqui estão as diretrizes gerais aplicadas aos cenários mais comuns:

### 1. Programas Acadêmicos (Graduação/Pós-Graduação)
*   **Limite máximo:** Geralmente, as universidades permitem a suspensão (trancamento) por um período total que varia entre **2 a 4 semestres letivos** ao longo de todo o curso. Algumas instituições permitem que esse período seja contínuo ou intercalado.
*   **Prazo para solicitação:** Deve ser feita, obrigatoriamente, **antes do início do período letivo** ou dentro do prazo estipulado no calendário acadêmico (geralmente nas primeiras semanas de aula). Solicitações feitas após o prazo costumam ser indeferidas, a menos que haja justificativa legal (como licença-maternidade ou serviço militar).

### 2. Programas de Benefícios Governamentais (Ex: FIES)
*   **Limite máximo:** No caso do FIES, por exemplo, a suspensão temporária pode ser solicitada por até **2 semestres consecutivos**.
*   **Prazo para solicitação:** Deve ser realizada através do sistema oficial (SisFIES) dentro dos prazos definidos pelo MEC para cada semestre. Geralmente, o pedido deve ser feito antes do encerramento do período de aditamento.

### 3. Planos de Saúde (Suspensão por iniciativa do beneficiário)
*   **Limite máximo:** A ANS (Agência Nacional de Saúde Suplementar) não estabelece um limite universal, mas as operadoras costumam permitir a suspensão por períodos que variam de **6 meses a 2 anos**, dependendo do contrato.
*   **Prazo para solicitação:** Deve ser solicitada com antecedência mínima (geralmente 30 dias) antes da data desejada para o início da suspensão, conforme as cláusulas contratuais.

---

### Como obter a resposta exata para o seu caso:
Para não correr riscos, você deve consultar as seguintes fontes:

1.  **O Regimento Interno ou Manual do Aluno:** Se for uma instituição de ensino.
2.  **O Edital do Programa:** Se for um benefício governamental ou bolsa de estudos.
3.  **O Contrato de Prestação de Serviços:** Se for um plano de saúde ou serviço privado.

**Recomendação:** Se você estiver tentando suspender um programa agora, verifique o **calendário oficial** da instituição imediatamente, pois perder o prazo de solicitação pode resultar na reprovação automática por faltas ou na cobrança indevida de mensalidades.

**Se você puder especificar qual é o programa (ex: FIES, curso de graduação X, plano de saúde Y), posso tentar fornecer informações mais direcionadas sobre as normas gerais daquele setor.**

CHUNKS — DENSO
[{'rank': 1,
  'cosine_similarity': 0.7784,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 1,
  'chunk': 2,
  'snippet': 'ular em que se encontra matriculado(a).\n'
             'CAPÍTULO XIII\n'
             'DA SUSPENSÃO DE PROGRAMA\n'
             'Art. 249. A suspensão de programa é a interrupção das atividades '
             'acadêmicas do(a) discente durante\n'
             'um período letivo regular, garantindo a ma…'},
 {'rank': 2,
  'cosine_similarity': 0.7763,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 1,
  'chunk': 3,
  'snippet': 'ralização curricular.\n'
             'Art. 250. A PREG pode conceder a suspensão de programa por um '
             'número de períodos superior ao\n'
             'limite fixado no § 1º do Art. 249 em casos justificados.\n'
             'Art. 251. Não pode ser solicitada suspensão de p…'},
 {'rank': 3,
  'cosine_similarity': 0.7584,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 2,
  'chunk': 0,
  'snippet': 'Parágrafo único. A suspensão de programa no primeiro período do '
             'curso pode ser concedido nos\n'
             'seguintes casos:\n'
             'I - motivo de saúde, devidamente comprovado pela Junta Médica da '
             'UFRPE;\n'
             'II - prestação de serviço militar obri…'},
 {'rank': 4,
  'cosine_similarity': 0.7482,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 2,
  'chunk': 1,
  'snippet': 'te desistir da suspensão durante esse período.\n'
             'Art. 253. A suspensão de programa referente a um período letivo '
             'regular também pode ser solicitada a\n'
             'posteriori, desde que as seguintes condições sejam todas '
             'satisfeitas:\n'
             'I …'},
 {'rank': 5,
  'cosine_similarity': 0.7477,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 3,
  'chunk': 0,
  'snippet': 'II- Para os cursos presenciais, até 2 (dois) períodos letivos, '
             'nos demais casos.\n'
             '§ 1º A prorrogação só pode ser concedida caso a COAA consiga '
             'elaborar um cronograma que\n'
             'demonstre a viabilidade de conclusão no prazo defin…'}]

RAG DENSO
O limite máximo para suspensões de programa é de 4 (quatro) períodos letivos regulares, consecutivos ou não [15_trancamento_cancelamento_suspensao, p. 1, trecho 2]. A suspensão deve ser solicitada a cada período letivo, dentro do prazo fixado no Calendário Acadêmico, que corresponde a 12 (doze) semanas após o início do período letivo regular [15_trancamento_cancelamento_suspensao, p. 1, trecho 2].

CHUNKS — TF-IDF
[{'rank': 1,
  'tfidf_cosine_similarity': 0.44,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 1,
  'chunk': 2,
  'snippet': 'ular em que se encontra matriculado(a).\n'
             'CAPÍTULO XIII\n'
             'DA SUSPENSÃO DE PROGRAMA\n'
             'Art. 249. A suspensão de programa é a interrupção das atividades '
             'acadêmicas do(a) discente durante\n'
             'um período letivo regular, garantindo a ma…'},
 {'rank': 2,
  'tfidf_cosine_similarity': 0.3405,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 2,
  'chunk': 0,
  'snippet': 'Parágrafo único. A suspensão de programa no primeiro período do '
             'curso pode ser concedido nos\n'
             'seguintes casos:\n'
             'I - motivo de saúde, devidamente comprovado pela Junta Médica da '
             'UFRPE;\n'
             'II - prestação de serviço militar obri…'},
 {'rank': 3,
  'tfidf_cosine_similarity': 0.3396,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 1,
  'chunk': 3,
  'snippet': 'ralização curricular.\n'
             'Art. 250. A PREG pode conceder a suspensão de programa por um '
             'número de períodos superior ao\n'
             'limite fixado no § 1º do Art. 249 em casos justificados.\n'
             'Art. 251. Não pode ser solicitada suspensão de p…'},
 {'rank': 4,
  'tfidf_cosine_similarity': 0.3336,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 2,
  'chunk': 1,
  'snippet': 'te desistir da suspensão durante esse período.\n'
             'Art. 253. A suspensão de programa referente a um período letivo '
             'regular também pode ser solicitada a\n'
             'posteriori, desde que as seguintes condições sejam todas '
             'satisfeitas:\n'
             'I …'},
 {'rank': 5,
  'tfidf_cosine_similarity': 0.2807,
  'paper': '15_trancamento_cancelamento_suspensao',
  'page': 2,
  'chunk': 2,
  'snippet': 's uma atividade acadêmica que não forma\n'
             'turma e cuja matrícula é feita pela coordenação elimina a '
             'exigência de cumprimento da condição do\n'
             'inciso II deste artigo.\n'
             'Art. 254. O período para suspensão de programa a posterior…'}]

RAG TF-IDF
O limite máximo para suspensões de programa é de 4 (quatro) períodos letivos regulares, consecutivos ou não [15_trancamento_cancelamento_suspensao, p. 1, trecho 2]. A suspensão deve ser solicitada a cada período letivo dentro do prazo fixado no Calendário Acadêmico, que corresponde a 12 (doze) semanas após o início do período letivo regular [15_trancamento_cancelamento_suspensao, p. 1, trecho 2].

==========================================================================================
PERGUNTA: Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?

SEM RETRIEVAL
O regime de observação do desempenho acadêmico (frequentemente chamado de "alerta" ou "condicional") é uma medida administrativa aplicada por instituições de ensino superior quando o estudante apresenta um rendimento acadêmico abaixo dos padrões mínimos exigidos pela universidade.

Embora as regras específicas variem conforme o regimento interno de cada instituição, a situação ocorre, de modo geral, nos seguintes cenários:

1.  **Baixo Rendimento Acadêmico (IRA/Coeficiente):** Quando o Índice de Rendimento Acadêmico (IRA), Coeficiente de Rendimento (CR) ou média global do aluno cai abaixo de um valor mínimo estabelecido (por exemplo, abaixo de 5,0 ou 6,0, dependendo da escala da instituição).
2.  **Reprovação Excessiva:** Quando o estudante é reprovado em um número elevado de disciplinas em um único período letivo ou acumula um percentual de reprovações que compromete a conclusão do curso dentro do prazo máximo permitido.
3.  **Desempenho Insuficiente em Disciplinas Obrigatórias:** Em alguns casos, a reprovação sucessiva em disciplinas específicas (geralmente de caráter fundamental ou pré-requisitos) pode levar ao regime de observação.
4.  **Evasão ou Abandono de Disciplinas:** Quando o aluno se matricula em um número de créditos inferior ao mínimo exigido ou abandona disciplinas sem o devido cancelamento formal, afetando sua progressão.

### O que acontece no regime de observação?
*   **Monitoramento:** O desempenho do aluno passa a ser acompanhado mais de perto pela coordenação do curso ou por uma comissão de graduação.
*   **Restrições de Matrícula:** É comum que o aluno em observação tenha restrições no número de créditos que pode cursar no semestre seguinte, sendo obrigado a priorizar as disciplinas em que foi reprovado.
*   **Orientação Acadêmica:** Muitas instituições exigem que o aluno participe de reuniões com orientadores acadêmicos ou tutores para traçar um plano de recuperação.
*   **Risco de Desligamento:** O regime de observação serve como um aviso formal. Caso o desempenho não melhore após um ou dois períodos letivos sob essa condição, o estudante pode ser submetido a um processo de desligamento (jubilamento) da instituição.

**Recomendação:** Para saber a regra exata que se aplica ao seu caso, você deve consultar o **Regimento Geral da Graduação** ou o **Projeto Pedagógico do seu curso** disponível no site da sua universidade, procurando pelos tópicos sobre "Desempenho Acadêmico", "Regime de Observação" ou "Desligamento".

CHUNKS — DENSO
[{'rank': 1,
  'cosine_similarity': 0.784,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 1,
  'chunk': 1,
  'snippet': 'istrado no histórico escolar do(a)\n'
             'discente, sendo o registro suprimido após a integralização do '
             'curso.\n'
             'Art. 322. É colocado em regime de observação do desempenho '
             'acadêmico o(a) discente que, no\n'
             'período letivo regular an…'},
 {'rank': 2,
  'cosine_similarity': 0.7651,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Regime de observação do desempenho acadêmico e cancelamento\n'
             'de programa\n'
             'CAPÍTULO XI\n'
             'DO REGIME DE OBSERVAÇÃO DO DESEMPENHO ACADÊMICO\n'
             'Art. 321. O regime de observação do …'},
 {'rank': 3,
  'cosine_similarity': 0.7531,
  'paper': '30_glossario',
  'page': 2,
  'chunk': 2,
  'snippet': 'ormativas, com base nas Diretrizes\n'
             'Curriculares Nacionais (DCN) e demais normativas, internas e '
             'externas à UFRPE.\n'
             'Regime de Observação e Desempenho Acadêmico (RODA): O discente '
             'que tiver acumulado 3\n'
             'insucessos, consecuti…'},
 {'rank': 4,
  'cosine_similarity': 0.7143,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 3,
  'chunk': 1,
  'snippet': 'nto e/ou reprovação) pela quarta vez ou mais, consecutiva ou '
             'não, em um mesmo\n'
             'componente curricular obrigatório ou seus equivalentes.\n'
             '§ 1º O desempenho acadêmico insuficiente é caracterizado após o '
             'término do período let…'},
 {'rank': 5,
  'cosine_similarity': 0.7104,
  'paper': '03_gestao_academica_dos_cursos',
  'page': 4,
  'chunk': 0,
  'snippet': '§ 1º Às instâncias referidas neste artigo deverão fornecer '
             'relatórios periódicos às coordenações dos\n'
             'cursos de graduação da UFRPE, quando solicitados pela COAA, '
             'visando ao atendimento pontual\n'
             'dos(as) discentes por esta c…'}]

RAG DENSO
Um(a) discente é colocado(a) no regime de observação do desempenho acadêmico (RODA) quando, no período letivo regular anterior, houver incorrido em insucesso (trancamento e/ou reprovação) pela terceira vez ou mais, consecutiva ou não, em um mesmo componente curricular obrigatório ou seus equivalentes [23_observacao_e_cancelamento_de_programa, p. 1, trecho 1; 30_glossario, p. 2, trecho 2].

CHUNKS — TF-IDF
[{'rank': 1,
  'tfidf_cosine_similarity': 0.6323,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Regime de observação do desempenho acadêmico e cancelamento\n'
             'de programa\n'
             'CAPÍTULO XI\n'
             'DO REGIME DE OBSERVAÇÃO DO DESEMPENHO ACADÊMICO\n'
             'Art. 321. O regime de observação do …'},
 {'rank': 2,
  'tfidf_cosine_similarity': 0.4371,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 1,
  'chunk': 1,
  'snippet': 'istrado no histórico escolar do(a)\n'
             'discente, sendo o registro suprimido após a integralização do '
             'curso.\n'
             'Art. 322. É colocado em regime de observação do desempenho '
             'acadêmico o(a) discente que, no\n'
             'período letivo regular an…'},
 {'rank': 3,
  'tfidf_cosine_similarity': 0.2488,
  'paper': '30_glossario',
  'page': 2,
  'chunk': 2,
  'snippet': 'ormativas, com base nas Diretrizes\n'
             'Curriculares Nacionais (DCN) e demais normativas, internas e '
             'externas à UFRPE.\n'
             'Regime de Observação e Desempenho Acadêmico (RODA): O discente '
             'que tiver acumulado 3\n'
             'insucessos, consecuti…'},
 {'rank': 4,
  'tfidf_cosine_similarity': 0.2388,
  'paper': '23_observacao_e_cancelamento_de_programa',
  'page': 1,
  'chunk': 2,
  'snippet': 'ensão de programa, presencialmente ou por meio\n'
             'eletrônico.\n'
             'Art. 324. No que diz respeito à preferência no preenchimento das '
             'vagas a que se refere o § 3º do\n'
             'Art. 236 deste Regulamento, o IEA dos(as) discentes em regime '
             'de…'},
 {'rank': 5,
  'tfidf_cosine_similarity': 0.2379,
  'paper': '18_tratamento_excepcional_de_faltas',
  'page': 2,
  'chunk': 0,
  'snippet': 'estado nem atividades de caráter experimental ou de atuação '
             'prática que não possam ser executadas\n'
             'pelo(a) discente.\n'
             '§ 1º O programa especial de estudos deve prever outros formatos '
             'para que sejam cumpridos os\n'
             'objetivos de…'}]

RAG TF-IDF
Um(a) discente é colocado(a) no regime de observação do desempenho acadêmico (RODA) quando, no período letivo regular anterior, houver incorrido em insucesso (trancamento e/ou reprovação) pela terceira vez ou mais, consecutiva ou não, em um mesmo componente curricular obrigatório ou seus equivalentes [23_observacao_e_cancelamento_de_programa, p. 1, trecho 1]. O glossário também reforça que o discente que tiver acumulado 3 insucessos, consecutivos ou não, em um dado componente curricular, passará a integrar o RODA [30_glossario, p. 2, trecho 2].

==========================================================================================
PERGUNTA: Como é calculada a nota final da seleção para monitoria?

SEM RETRIEVAL
O cálculo da nota final em uma seleção de monitoria não possui um padrão único, pois **depende exclusivamente do edital específico** publicado pela instituição de ensino ou pelo departamento responsável.

No entanto, na maioria das universidades brasileiras, a nota final é composta pela soma ponderada de diferentes etapas. As mais comuns são:

### 1. Componentes comuns da nota
*   **Média Acadêmica (ou Coeficiente de Rendimento):** É a nota obtida nas disciplinas cursadas pelo aluno. Geralmente, tem um peso fixo na nota final para garantir que o monitor tenha bom desempenho na matéria que irá lecionar.
*   **Prova Escrita ou Teórica:** Avalia o conhecimento técnico do candidato sobre o conteúdo da disciplina.
*   **Prova Prática ou Didática:** Avalia a capacidade do aluno de transmitir o conhecimento (ex: uma aula expositiva de 10 a 15 minutos sobre um tema sorteado).
*   **Entrevista:** Avalia a disponibilidade de horário, motivação e perfil do candidato para lidar com os alunos.

### 2. Como o cálculo é feito (Exemplo)
O edital define o "peso" de cada etapa. Por exemplo:
*   **Média na disciplina:** Peso 4,0
*   **Prova escrita:** Peso 3,0
*   **Prova didática:** Peso 3,0

A fórmula seria:
**Nota Final = (Nota da Disciplina × 0,4) + (Nota da Prova Escrita × 0,3) + (Nota da Prova Didática × 0,3)**

### 3. Critérios de Desempate
O edital também estabelece como proceder em caso de empate. Os critérios mais frequentes são:
*   Maior nota na disciplina objeto da monitoria.
*   Maior coeficiente de rendimento global (média geral do curso).
*   Maior período cursado (aluno mais avançado no curso).
*   Sorteio público (em último caso).

### O que você deve fazer:
Para saber exatamente como a sua nota será calculada, você deve:
1.  **Ler o Edital:** Procure a seção intitulada "Do Processo Seletivo", "Da Avaliação" ou "Dos Critérios de Seleção".
2.  **Verificar os Pesos:** Veja se alguma etapa tem caráter eliminatório (ex: tirar menos que 7,0 na prova escrita desclassifica o candidato automaticamente).
3.  **Consultar a Secretaria:** Caso o edital não esteja claro, entre em contato com a secretaria do departamento que está oferecendo a vaga.

**Resumo:** Não existe uma regra universal; a fórmula matemática e os pesos de cada etapa são definidos pela comissão organizadora de cada processo seletivo e devem estar descritos obrigatoriamente no edital.

CHUNKS — DENSO
[{'rank': 1,
  'cosine_similarity': 0.7801,
  'paper': '26_monitoria',
  'page': 2,
  'chunk': 0,
  'snippet': 'I - nota atribuída pela banca examinadora na ocasião da seleção '
             'através da aplicação de prova teórica,\n'
             'prova prática, prova didática ou outro instrumento avaliativo '
             'que a banca julgue pertinente conforme\n'
             'especificado em …'},
 {'rank': 2,
  'cosine_similarity': 0.7501,
  'paper': '26_monitoria',
  'page': 1,
  'chunk': 3,
  'snippet': 'no caso de não haver quantitativo de professores específicos da '
             'área, fica a\n'
             'Coordenação do curso responsável por convidar professores do '
             'curso para compor a banca, da qual\n'
             'participará o professor responsável pelos compo…'},
 {'rank': 3,
  'cosine_similarity': 0.745,
  'paper': '26_monitoria',
  'page': 2,
  'chunk': 1,
  'snippet': 'discentes que obtiverem NF superior a\n'
             '7,0 (sete).\n'
             'Art. 371. É considerado(a) apto a participar da seleção de '
             'monitoria o(a) discente que atender aos\n'
             'seguintes critérios:\n'
             'I - apresentar MC igual ou superior a 7,0 (sete); …'},
 {'rank': 4,
  'cosine_similarity': 0.7151,
  'paper': '26_monitoria',
  'page': 1,
  'chunk': 2,
  'snippet': 'o edital.\n'
             'Art. 368. Haverá uma única lista de classificação contendo as '
             'nomenclaturas identificando a situação do\n'
             'candidato quanto a ser bolsista ou voluntário.\n'
             'I - bolsista: É o estudante aprovado e classificado, que es…'},
 {'rank': 5,
  'cosine_similarity': 0.7149,
  'paper': '26_monitoria',
  'page': 3,
  'chunk': 0,
  'snippet': 'Termos de compromisso dos(as) novos(as) monitores(as) que foram '
             'selecionados(as); e\n'
             'VII- avaliar e emitir parecer sobre relatório final de '
             'atividades elaborado pelo(a) monitor(a).\n'
             'Art. 377. É vedada a concessão de vagas …'}]

RAG DENSO
A nota final (NF) da seleção para monitoria é calculada pela média aritmética das seguintes três notas [26_monitoria, p. 1, trecho 3]:

1. Nota atribuída pela banca examinadora (através de prova teórica, prática, didática ou outro instrumento avaliativo definido em edital) [26_monitoria, p. 2, trecho 0];
2. Média de conclusão (MC) do(a) discente [26_monitoria, p. 2, trecho 0];
3. Nota do(a) discente (NE) no componente curricular objeto da seleção [26_monitoria, p. 2, trecho 0].

Caso o objeto da seleção seja um conjunto de componentes curriculares, a NE será a média aritmética das notas obtidas em cada um dos componentes cursados [26_monitoria, p. 2, trecho 0].

CHUNKS — TF-IDF
[{'rank': 1,
  'tfidf_cosine_similarity': 0.2616,
  'paper': '26_monitoria',
  'page': 2,
  'chunk': 0,
  'snippet': 'I - nota atribuída pela banca examinadora na ocasião da seleção '
             'através da aplicação de prova teórica,\n'
             'prova prática, prova didática ou outro instrumento avaliativo '
             'que a banca julgue pertinente conforme\n'
             'especificado em …'},
 {'rank': 2,
  'tfidf_cosine_similarity': 0.2191,
  'paper': '07_periodos_avaliacao_rendimento',
  'page': 3,
  'chunk': 2,
  'snippet': 'final) igual à média parcial.\n'
             'Art. 139. Para o(a) discente que realiza prova final, sua média '
             'final é calculada como a média aritmética\n'
             'entre a média parcial e a nota da prova final, e será '
             'considerado(a) aprovado(a), qu…'},
 {'rank': 3,
  'tfidf_cosine_similarity': 0.2184,
  'paper': '07_periodos_avaliacao_rendimento',
  'page': 3,
  'chunk': 1,
  'snippet': 'iores notas dentre as\n'
             'três verificações de aprendizagem (1ª V.A., 2ª V.A. e 3ª V.A.), '
             'sendo considerado(a) aprovado(a),\n'
             'quanto à avaliação de aprendizagem, o(a) discente que tem média '
             'parcial igual ou superior a 7,0 (set…'},
 {'rank': 4,
  'tfidf_cosine_similarity': 0.216,
  'paper': '26_monitoria',
  'page': 1,
  'chunk': 0,
  'snippet': 'UFRPE — Regulamento Geral da Graduação (PREG, 2024)\n'
             'Programa de monitoria\n'
             'TÍTULO XIV\n'
             'DOS PROGRAMAS DA PREG\n'
             'CAPÍTULO I\n'
             'DA MONITORIA\n'
             'Art. 362. O programa de monitoria tem como objetivo estimular a '
             'cooperação entre o corpo …'},
 {'rank': 5,
  'tfidf_cosine_similarity': 0.189,
  'paper': '26_monitoria',
  'page': 3,
  'chunk': 0,
  'snippet': 'Termos de compromisso dos(as) novos(as) monitores(as) que foram '
             'selecionados(as); e\n'
             'VII- avaliar e emitir parecer sobre relatório final de '
             'atividades elaborado pelo(a) monitor(a).\n'
             'Art. 377. É vedada a concessão de vagas …'}]

RAG TF-IDF
A nota final (NF) da seleção para monitoria é composta pelos seguintes critérios:

*   Nota atribuída pela banca examinadora na ocasião da seleção, por meio de prova teórica, prática, didática ou outro instrumento avaliativo definido em edital [26_monitoria, p. 2, trecho 0];
*   Média de conclusão (MC) do(a) discente [26_monitoria, p. 2, trecho 0];
*   Nota do(a) discente (NE) no componente curricular objeto da seleção [26_monitoria, p. 2, trecho 0].

Caso o objeto da seleção seja um conjunto de componentes curriculares, a NE será calculada pela média aritmética das notas obtidas pelo(a) discente em cada um dos componentes cursados [26_monitoria, p. 2, trecho 0]. Se o(a) discente tiver sido dispensado de cursar o componente por aproveitamento, ele deve apresentar o histórico que originou o aproveitamento para que a nota seja computada [26_monitoria, p. 2, trecho 0].

## 6. Avaliação manual das 10 respostas

Preencha `True`/`False` depois de ler cada resposta e, nos casos com retrieval, os chunks exibidos. Para a baseline sem retrieval, suporte e citação não se aplicam.

In [ ]:
evaluation_sheet = [
    {
        "answer_id": index,
        "question": item["question"],
        "method": item["method"],
        "correct": None,
        "supported_by_chunks": None if item["method"] != "no_retrieval" else "N/A",
        "cites_right_chunk": None if item["method"] != "no_retrieval" else "N/A",
        "notes": "",
    }
    for index, item in enumerate(generated_answers, start=1)
]
evaluation_sheet

[{'answer_id': 1,
  'question': 'Por quanto tempo um(a) discente pode manter a condição de aluno especial?',
  'method': 'dense',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''},
 {'answer_id': 2,
  'question': 'Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?',
  'method': 'no_retrieval',
  'correct': None,
  'supported_by_chunks': 'N/A',
  'cites_right_chunk': 'N/A',
  'notes': ''},
 {'answer_id': 3,
  'question': 'Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?',
  'method': 'dense',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''},
 {'answer_id': 4,
  'question': 'Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?',
  'method': 'tfidf',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''},
 {'answer_id': 5,
  'question': 'Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?',
  'method': 'no_retrieval',
  'correct': None,
  'supported_by_chunks': 'N/A',
  'cites_right_chunk': 'N/A',
  'notes': ''},
 {'answer_id': 6,
  'question': 'Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?',
  'method': 'dense',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''},
 {'answer_id': 7,
  'question': 'Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?',
  'method': 'tfidf',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''},
 {'answer_id': 8,
  'question': 'Como é calculada a nota final da seleção para monitoria?',
  'method': 'no_retrieval',
  'correct': None,
  'supported_by_chunks': 'N/A',
  'cites_right_chunk': 'N/A',
  'notes': ''},
 {'answer_id': 9,
  'question': 'Como é calculada a nota final da seleção para monitoria?',
  'method': 'dense',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''},
 {'answer_id': 10,
  'question': 'Como é calculada a nota final da seleção para monitoria?',
  'method': 'tfidf',
  'correct': None,
  'supported_by_chunks': None,
  'cites_right_chunk': None,
  'notes': ''}]

In [2]:
# Criar a planilha de avaliação sem executar o RAG

perguntas = [
    "Por quanto tempo um(a) discente pode manter a condição de aluno especial?",
    "Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?",
    "Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?",
    "Como é calculada a nota final da seleção para monitoria?"
]

casos = [
    (1, perguntas[0], "dense"),
    (2, perguntas[1], "no_retrieval"),
    (3, perguntas[1], "dense"),
    (4, perguntas[1], "tfidf"),
    (5, perguntas[2], "no_retrieval"),
    (6, perguntas[2], "dense"),
    (7, perguntas[2], "tfidf"),
    (8, perguntas[3], "no_retrieval"),
    (9, perguntas[3], "dense"),
    (10, perguntas[3], "tfidf"),
]

evaluation_sheet = [
    {
        "answer_id": num,
        "question": pergunta,
        "method": metodo,
        "correct": None,
        "supported_by_chunks": "N/A" if metodo == "no_retrieval" else None,
        "cites_right_chunk": "N/A" if metodo == "no_retrieval" else None,
        "notes": ""
    }
    for num, pergunta, metodo in casos
]

print("Planilha de avaliação criada com sucesso!")

Planilha de avaliação criada com sucesso!

In [5]:
# Avaliação 1 - Aluno especial (Dense)

evaluation_sheet[0].update({
    "correct": True,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "A resposta informa corretamente o limite de "
        "quatro períodos letivos consecutivos, conforme "
        "o Art. 180, §3º. O chunk recuperado sustenta "
        "a resposta e a citação corresponde à fonte."
    )
})

evaluation_sheet[0]

{'answer_id': 1,
 'question': 'Por quanto tempo um(a) discente pode manter a condição de aluno especial?',
 'method': 'dense',
 'correct': True,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'A resposta informa corretamente o limite de quatro períodos letivos consecutivos, conforme o Art. 180, §3º. O chunk recuperado sustenta a resposta e a citação corresponde à fonte.'}

In [3]:
# Avaliação 2 - Suspensão de programa (Sem Retrieval)

evaluation_sheet[1].update({
    "correct": False,
    "supported_by_chunks": "N/A",
    "cites_right_chunk": "N/A",
    "notes": (
        "A resposta é genérica e não apresenta corretamente "
        "as regras específicas da UFRPE. Conforme o Art. 249, "
        "o limite é de quatro períodos letivos regulares, "
        "consecutivos ou não, e a solicitação deve ocorrer "
        "dentro do prazo de 12 semanas após o início do "
        "período letivo. O modelo também incluiu informações "
        "irrelevantes sobre FIES e planos de saúde."
    )
})

evaluation_sheet[1]

{'answer_id': 2,
 'question': 'Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?',
 'method': 'no_retrieval',
 'correct': False,
 'supported_by_chunks': 'N/A',
 'cites_right_chunk': 'N/A',
 'notes': 'A resposta é genérica e não apresenta corretamente as regras específicas da UFRPE. Conforme o Art. 249, o limite é de quatro períodos letivos regulares, consecutivos ou não, e a solicitação deve ocorrer dentro do prazo de 12 semanas após o início do período letivo. O modelo também incluiu informações irrelevantes sobre FIES e planos de saúde.'}

In [8]:
# Avaliação 3 - Suspensão (Dense)
evaluation_sheet[2].update({
    "correct": True,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "Resposta correta conforme o Art. 249. "
        "O recuperador denso encontrou o trecho relevante "
        "no documento 15_trancamento_cancelamento_suspensao, "
        "página 1, trecho 2, citado corretamente."
    )
})
evaluation_sheet[2]

{'answer_id': 3,
 'question': 'Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?',
 'method': 'dense',
 'correct': True,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'Resposta correta conforme o Art. 249. O recuperador denso encontrou o trecho relevante no documento 15_trancamento_cancelamento_suspensao, página 1, trecho 2, citado corretamente.'}

In [11]:
# Avaliação 4 - Suspensão de programa (TF-IDF)

evaluation_sheet[3].update({
    "correct": True,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "Resposta correta conforme o Art. 249 do Regulamento "
        "Geral da Graduação da UFRPE. O TF-IDF recuperou "
        "o trecho relevante do documento "
        "15_trancamento_cancelamento_suspensao, "
        "página 1, trecho 2. A resposta está fundamentada "
        "e apresenta a citação correspondente."
    )
})
evaluation_sheet[3]
# Visualizar avaliações

{'answer_id': 4,
 'question': 'Qual é o limite máximo de suspensões de programa e até quando a suspensão deve ser solicitada?',
 'method': 'tfidf',
 'correct': True,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'Resposta correta conforme o Art. 249 do Regulamento Geral da Graduação da UFRPE. O TF-IDF recuperou o trecho relevante do documento 15_trancamento_cancelamento_suspensao, página 1, trecho 2. A resposta está fundamentada e apresenta a citação correspondente.'}

In [12]:
# Avaliação 5 - Regime de Observação (Sem Retrieval)

evaluation_sheet[4].update({
    "correct": False,
    "supported_by_chunks": "N/A",
    "cites_right_chunk": "N/A",
    "notes": (
        "A resposta é genérica e não apresenta o critério "
        "específico do Art. 322 do regulamento da UFRPE. "
        "O regime de observação ocorre após três ou mais "
        "insucessos, consecutivos ou não, em um mesmo "
        "componente curricular obrigatório ou equivalente. "
        "O modelo menciona fatores gerais, como baixo "
        "rendimento e abandono, sem identificar essa regra."
    )
})
evaluation_sheet[4]
# Visualizar avaliações atualizadas

{'answer_id': 5,
 'question': 'Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?',
 'method': 'no_retrieval',
 'correct': False,
 'supported_by_chunks': 'N/A',
 'cites_right_chunk': 'N/A',
 'notes': 'A resposta é genérica e não apresenta o critério específico do Art. 322 do regulamento da UFRPE. O regime de observação ocorre após três ou mais insucessos, consecutivos ou não, em um mesmo componente curricular obrigatório ou equivalente. O modelo menciona fatores gerais, como baixo rendimento e abandono, sem identificar essa regra.'}

In [14]:
# Avaliação 6 - Regime de Observação (RAG Denso)

evaluation_sheet[5].update({
    "correct": True,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "A resposta está correta conforme o Art. 322 do "
        "Regulamento Geral da Graduação da UFRPE. "
        "O recuperador denso encontrou o trecho relevante "
        "no documento 23_observacao_e_cancelamento_de_programa, "
        "página 1, trecho 1, além do glossário, página 2, "
        "trecho 2. Ambos sustentam a regra dos três "
        "insucessos, e as citações correspondem aos "
        "chunks recuperados."
    )
})
evaluation_sheet[5]
# Visualizar avaliações atualizadas

{'answer_id': 6,
 'question': 'Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?',
 'method': 'dense',
 'correct': True,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'A resposta está correta conforme o Art. 322 do Regulamento Geral da Graduação da UFRPE. O recuperador denso encontrou o trecho relevante no documento 23_observacao_e_cancelamento_de_programa, página 1, trecho 1, além do glossário, página 2, trecho 2. Ambos sustentam a regra dos três insucessos, e as citações correspondem aos chunks recuperados.'}

In [17]:
# Avaliação 7 - Regime de Observação (TF-IDF)

evaluation_sheet[6].update({
    "correct": True,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "Resposta correta conforme o Art. 322 do Regulamento "
        "Geral da Graduação da UFRPE. O TF-IDF recuperou "
        "o trecho relevante do documento "
        "23_observacao_e_cancelamento_de_programa, "
        "página 1, trecho 1, e o glossário, página 2, "
        "trecho 2. Ambos apresentam a regra dos três "
        "insucessos, e as citações correspondem "
        "aos chunks recuperados."
    )
})
evaluation_sheet[6]
# Visualizar avaliações atualizadas

{'answer_id': 7,
 'question': 'Em que situação um(a) discente é colocado(a) no regime de observação do desempenho acadêmico?',
 'method': 'tfidf',
 'correct': True,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'Resposta correta conforme o Art. 322 do Regulamento Geral da Graduação da UFRPE. O TF-IDF recuperou o trecho relevante do documento 23_observacao_e_cancelamento_de_programa, página 1, trecho 1, e o glossário, página 2, trecho 2. Ambos apresentam a regra dos três insucessos, e as citações correspondem aos chunks recuperados.'}

In [19]:
# Avaliação 8 - Seleção para monitoria (Sem Retrieval)

evaluation_sheet[7].update({
    "correct": False,
    "supported_by_chunks": "N/A",
    "cites_right_chunk": "N/A",
    "notes": (
        "A resposta não apresenta a fórmula específica do "
        "regulamento da UFRPE. O modelo fornece um exemplo "
        "genérico de média ponderada com pesos 40%, 30% e 30%, "
        "enquanto a nota final da seleção para monitoria "
        "corresponde à média aritmética das notas da banca "
        "examinadora, média de conclusão (MC) e nota do "
        "estudante no componente curricular (NE)."
    )
})
evaluation_sheet[7]
# Visualizar avaliações atualizadas

{'answer_id': 8,
 'question': 'Como é calculada a nota final da seleção para monitoria?',
 'method': 'no_retrieval',
 'correct': False,
 'supported_by_chunks': 'N/A',
 'cites_right_chunk': 'N/A',
 'notes': 'A resposta não apresenta a fórmula específica do regulamento da UFRPE. O modelo fornece um exemplo genérico de média ponderada com pesos 40%, 30% e 30%, enquanto a nota final da seleção para monitoria corresponde à média aritmética das notas da banca examinadora, média de conclusão (MC) e nota do estudante no componente curricular (NE).'}

In [21]:
# Avaliação 9 - Seleção para Monitoria (RAG Denso)

evaluation_sheet[8].update({
    "correct": True,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "A resposta apresenta corretamente a média aritmética "
        "das três notas: banca examinadora, média de conclusão "
        "(MC) e nota no componente curricular (NE). "
        "O recuperador denso encontrou o documento 26_monitoria, "
        "página 2, trecho 0, que contém os componentes do cálculo. "
        "As citações correspondem a chunks recuperados, embora "
        "a referência à página 1, trecho 3, precise de confirmação "
        "com o conteúdo integral do chunk."
    )
})

evaluation_sheet[8]
# Visualizar avaliações

{'answer_id': 9,
 'question': 'Como é calculada a nota final da seleção para monitoria?',
 'method': 'dense',
 'correct': True,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'A resposta apresenta corretamente a média aritmética das três notas: banca examinadora, média de conclusão (MC) e nota no componente curricular (NE). O recuperador denso encontrou o documento 26_monitoria, página 2, trecho 0, que contém os componentes do cálculo. As citações correspondem a chunks recuperados, embora a referência à página 1, trecho 3, precise de confirmação com o conteúdo integral do chunk.'}

In [23]:
# Avaliação 10 - Seleção para Monitoria (TF-IDF)

evaluation_sheet[9].update({
    "correct": False,
    "supported_by_chunks": True,
    "cites_right_chunk": True,
    "notes": (
        "A resposta identifica corretamente os três componentes "
        "da nota final: nota da banca examinadora, média de "
        "conclusão (MC) e nota no componente curricular (NE). "
        "Entretanto, não informa explicitamente que a nota "
        "final é a média aritmética simples desses valores, "
        "deixando incompleto o cálculo solicitado. "
        "O TF-IDF recuperou o documento 26_monitoria, "
        "página 2, trecho 0, e a resposta cita corretamente "
        "a fonte utilizada. Classificada como incompleta "
        "pelo critério de correção estrito."
    )
})
evaluation_sheet[9]
# Exibir a tabela completa

{'answer_id': 10,
 'question': 'Como é calculada a nota final da seleção para monitoria?',
 'method': 'tfidf',
 'correct': False,
 'supported_by_chunks': True,
 'cites_right_chunk': True,
 'notes': 'A resposta identifica corretamente os três componentes da nota final: nota da banca examinadora, média de conclusão (MC) e nota no componente curricular (NE). Entretanto, não informa explicitamente que a nota final é a média aritmética simples desses valores, deixando incompleto o cálculo solicitado. O TF-IDF recuperou o documento 26_monitoria, página 2, trecho 0, e a resposta cita corretamente a fonte utilizada. Classificada como incompleta pelo critério de correção estrito.'}

In [24]:
import pandas as pd

pd.DataFrame(evaluation_sheet)

,answer_id,question,method,correct,supported_by_chunks,cites_right_chunk,notes
0,1,Por quanto tempo um(a) discente pode manter a ...,dense,True,True,True,A resposta informa corretamente o limite de qu...
1,2,Qual é o limite máximo de suspensões de progra...,no_retrieval,False,N/A,N/A,A resposta é genérica e não apresenta corretam...
2,3,Qual é o limite máximo de suspensões de progra...,dense,True,True,True,Resposta correta conforme o Art. 249. O recupe...
3,4,Qual é o limite máximo de suspensões de progra...,tfidf,True,True,True,Resposta correta conforme o Art. 249 do Regula...
4,5,Em que situação um(a) discente é colocado(a) n...,no_retrieval,False,N/A,N/A,A resposta é genérica e não apresenta o critér...
5,6,Em que situação um(a) discente é colocado(a) n...,dense,True,True,True,A resposta está correta conforme o Art. 322 do...
6,7,Em que situação um(a) discente é colocado(a) n...,tfidf,True,True,True,Resposta correta conforme o Art. 322 do Regula...
7,8,Como é calculada a nota final da seleção para ...,no_retrieval,False,N/A,N/A,A resposta não apresenta a fórmula específica ...
8,9,Como é calculada a nota final da seleção para ...,dense,True,True,True,A resposta apresenta corretamente a média arit...
9,10,Como é calculada a nota final da seleção para ...,tfidf,False,True,True,A resposta identifica corretamente os três com...

## 7. Diagnóstico de duas respostas erradas

Depois da avaliação, escolha dois `answer_id` incorretos. Marque **retrieval** se os chunks necessários não chegaram ao modelo; marque **generation** se os chunks eram adequados, mas a resposta os interpretou mal, ignorou evidências ou citou o trecho errado.

In [25]:
# Seção 7 - Diagnóstico de duas respostas incorretas

failure_analysis = [
    {
        "answer_id": 10,
        "failure_source": "generation",
        "justification": (
            "O TF-IDF recuperou o documento correto sobre monitoria, "
            "incluindo o chunk da página 2, trecho 0. "
            "Entretanto, a resposta identificou os três componentes "
            "da nota final sem informar que o cálculo utiliza a "
            "média aritmética simples. Trata-se de uma falha de "
            "geração por omissão de informação relevante, "
            "e não de recuperação."
        )
    },
    {
        "answer_id": 2,
        "failure_source": "generation",
        "justification": (
            "O modelo respondeu sem retrieval e apresentou regras "
            "genéricas sobre suspensão de programas. "
            "Não identificou o limite de quatro períodos letivos "
            "nem o prazo de doze semanas previsto no Art. 249 "
            "do regulamento da UFRPE. A falha ocorreu na geração "
            "sem contexto documental. Não é uma falha de retrieval, "
            "pois nenhum recuperador foi utilizado."
        )
    }
]

import pandas as pd
pd.DataFrame(failure_analysis)

   answer_id failure_source                                      justification
0         10     generation  O TF-IDF recuperou o documento correto sobre m...
1          2     generation  O modelo respondeu sem retrieval e apresentou ...

## 8. Risco de busca responsável

**Atualidade (freshness):** o índice é uma fotografia do Regulamento Geral da Graduação de 2024 no momento da ingestão. O próprio regulamento já traz dispositivos alterados por resoluções posteriores ("redação dada pela Resolução..."). Se o CEPE aprovar uma nova resolução mudando, por exemplo, o limite de suspensões de programa ou os critérios do RODA, o sistema continuará respondendo a regra antiga com citação e aparência de autoridade, e um(a) discente pode perder um prazo ou tomar uma decisão acadêmica errada.

**Mitigação:** registrar no metadado de cada chunk a versão e a data do regulamento, mostrar essa data junto de toda resposta ("segundo o Regulamento PREG 2024") e reindexar automaticamente quando a PREG publicar uma nova versão ou resolução, removendo os chunks do documento substituído. Para decisões com prazo, a resposta deve recomendar a confirmação com a coordenação ou o DRCA.